import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAtomValue } from 'jotai'
import { tenTimesPageAtom } from '../atoms/pageAtom'
import Component from '../components/Component'

const Home: NextPage = () => {
    const page = useAtomValue(tenTimesPageAtom)
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Page number: {page}
                </h1>

                <Component />
            </main>

            <footer className={styles.footer}>
                <a
                    href="/__repl"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Built on
                    <span className={styles.logo}>
                        <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
                    </span>
                    Replit
                </a>
            </footer>
        </div>
    )
}

export default Home
